### PR TITLE
generate_package: Modify for imports in coala to work

### PR DESCRIPTION
**Pull request by Adrianzatreanu**

### CODE REVIEW

**Comment by sils1297** [comment]
can you actually add an explanation to the commit message?

**Comment by Adrianzatreanu** [comment]
yes, done

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala-bears/pull/709/commits/844f2c65b769420f3ae82c6ea0f940bab5f43032

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
