### PR TITLE
Decorators: Use the package

### PR DESCRIPTION
**Pull request by Adrianzatreanu**
Decorators are now in the coala_decorators module
and need to be imported correctly.

### CODE REVIEW

**Comment by sils1297** [comment]
seems very incomplete

**Comment by Adrianzatreanu** [comment]
what is incomplete at it?

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala-bears/pull/459/commits/5e4af9788454689131adc4174157992f5f216987

**Comment by Adrianzatreanu** [comment]
reack 6128792

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
