### PR TITLE
GitCommitBear: body_line_length

### PR DESCRIPTION
**Pull request by theaverageguy**
Fixes https://github.com/coala-analyzer/coala-bears/issues/137

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
Hey. You do not seem to be assigned for the issue you are working for. Would you like me to assign you?

**Comment by theaverageguy** [comment]
Please do! :)

**Comment by Adrianzatreanu** [comment]
Btw, one of the errors is that your HEAD @ the commit message is too long. please reduce it, using ``git commit --amend``

**Comment by theaverageguy** [comment]
Can this be reviewed now? I fixed the length.

**Comment by sils1297** [comment]
Hey, can you fix your commit message according to http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html ?

**Comment by tushar-rishav** [comment]
@sils1297  @Adrianzatreanu  We shouldn't have assigned him this issue. He's already doing https://github.com/coala-analyzer/coala-bears/pull/148  :(

**Comment by tushar-rishav** [comment]
@theaverageguy  Please refrain from doing multiple newcomers bug. Moreover, do fix your past PR before moving to next.

**Comment by theaverageguy** [comment]
Err... I remembered it as a low bug. Anyways, will take care.

**Comment by Adrianzatreanu** [comment]
@tushar-rishav i did not know that, my bad!

**Pull request closed without merging**
