### PR TITLE
requirements: Allow higher coala

### PR DESCRIPTION
**Pull request by sils1297**

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
command timed out, this is so weird.

**Comment by sils1297** [comment]
this happened multiple times, I restarted those tests like 5 times we shouldn't merge this.

**Comment by sils1297** [comment]
but I don't think it's an issue with my commit, maybe the nltk thing is unstable?

**Comment by sils1297** [comment]
CC @Makman2 we need help :(

**Comment by SanketDG** [comment]
I restarted the build 

Old build: https://circleci.com/gh/coala-analyzer/coala-bears/1199

**Pull request closed without merging**
