### PR TITLE
ESLintBear: Return on empty output

### PR DESCRIPTION
**Pull request by sils1297**
Fixes https://github.com/coala-analyzer/coala-bears/issues/727

@underyx can you review this?

### CODE REVIEW

**Comment by underyx** [comment]
@sils1297 how do you trigger empty output?

**Comment by sils1297** [comment]
by providing a good file without errors I think

**Comment by Adrianzatreanu** [comment]
wip as its not even passing tests

**Comment by sils1297** [comment]
damn!

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala-analyzer.org/ - http://viperdev.io/ - http://gitmate.com/

**Comment by Adrianzatreanu** [comment]
Hi,

it looks like your PR is out of date and needs a rebase. [This page](http://coala.readthedocs.io/en/latest/Developers/Git_Basics.html) may help you to get started on this. (*Do not press the update branch button. It's evil.*)

We also have a quick video tutorial on how to rebase: [https://asciinema.org/a/78683](https://asciinema.org/a/78683). That should help you understand the basics of how it works and what you should be doing.

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix it up for you - just tell us :).

Ping us on [our gitter channel](https://gitter.im/coala-analyzer/coala) if you need help!

**Comment by sils1297** [comment]
Oh thanks for the information!  I wouldn't be able to do it otherwise, I was really scared to ask :(

**Comment by AbdealiJK** [comment]
I'm closing this, as it's not needed  Can't see any usecase where the patch works

**Comment by sils1297** [comment]
Cool I'll look out for a reproduction. If I don't manage, this is for the better.

**Comment by underyx** [comment]
@sils1297 I just ran ESLint on a project with no errors and it had no output.

**Pull request closed without merging**
