### PR TITLE
Move Lua to the deps in .ci/deps.sh.

### PR DESCRIPTION
**Pull request by vivek425ster**
Solves https://github.com/coala-analyzer/coala-bears/issues/170

### CODE REVIEW

**Comment by SanketDG** [comment]
unack 7bdeffc

needs proper commit message and rebase.

**Comment by SanketDG** [comment]
You might want to take a look at http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html#keeping-your-fork-in-sync

**Comment by sils1297** [comment]
hey, please don't push the update branch button, it's pretty evil :/

Is that in our newcomers tutorial btw.? Everyone still does it :(

**Comment by vivek425ster** [comment]
@sils1297 Sorry. 
No it's not in the newcomer tutorial. 
I generally update my branch using `git pull`.
 I thought that this Update branch would automatically update my branch.

**Comment by sils1297** [comment]
yeah we use the rebase, we have it described in the git tutorial also
somewhere...

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-10 17:51 GMT+01:00 vivek425ster <notifications@github.com>:

**Comment by sils1297** [comment]
if you need further help ping us on gitter

**Comment by Adrianzatreanu** [comment]
ack b291811

**Comment by sils1297** [comment]
ack b291811 ?

**Comment by sils1297** [comment]
oh the panding one is appveyor... nm.

**Comment by Adrianzatreanu** [comment]
yes, its only a small change that should be fine and passed on circleci :)

**Comment by Makman2** [comment]
unack b291811, sorry the commit message :/
Please leave out the trailing dot inside the shortlog, and when you are at it there's also a spacing issue inside the commit body^^

**Comment by AbdealiJK** [comment]
ack 	 fb31a80

**Comment by AbdealiJK** [comment]
@rultor merge

**Pull request merged**
