### PR TITLE
bears: Remove CheckPrerequisites

### PR DESCRIPTION
**Pull request by SanketDG**
The Lint class has been updated with a newer prerequisite checking
function that checks for two new things:

prerequisite_command : this command, if exists, should return an
exitcode of 0.
prerequisite_fail_msg : message to display if exitcode != 0

This was introduced in:
https://github.com/coala-analyzer/coala/commit/188a942

This renders the CheckPrerequisites module invalid. This commit
removes this redundant class and also refactors bears that used
this module.

Fixes https://github.com/coala-analyzer/coala-bears/issues/146

### CODE REVIEW

**Comment by AbdealiJK** [comment]
Other than the back slash this looks good to me.
But I'd love a second review preferably from whoever reviewed https://github.com/coala-analyzer/coala/commit/188a942

**Comment by Adrianzatreanu** [comment]
this looks good :)

**Comment by sils1297** [comment]
ah yeah gitmate still fails on renamings and creations of files and will stay "in progress" forever...

**Comment by sils1297** [comment]
I'll run coala-incremental manually on this one, let's see what happens :P

**Comment by sils1297** [comment]
to test my workaround

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
