### PR TITLE
IndentationBear: Explain that it is experimental

### PR DESCRIPTION
**Pull request by abhsag24**

### CODE REVIEW

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala-bears/pull/540/commits/1616bfd6ae8ec86af0daac9f86d7b6d485949b42 - rebaseneeded though!

**Comment by abhsag24** [comment]
reack ca57333

**Comment by abhsag24** [comment]
reack ca57333

**Comment by abhsag24** [comment]
reack 56ee9d4

**Comment by abhsag24** [comment]
@rultor merge

**Pull request merged**
