### PR TITLE
Bears: Add Indentation Bear

### PR DESCRIPTION
**Pull request by abhsag24**
It is a generic indent bear, which looks for a start and end
indent, it also leaves out comments, if they are specified and it
also check for false indents in strings eg: "{" where { is an
indent start

Fixes https://github.com/coala-analyzer/coala-bears/issues/40

### CODE REVIEW

**Comment by sils1297** [comment]
hey, I'm just merging https://github.com/coala-analyzer/coala-bears/pull/89 , please rebase - that should fix AppVeyor.

**Comment by sils1297** [comment]
fyi the author info in the commit doesn't seem to match, may affect indiahacks scoring

**Comment by abhsag24** [comment]
ready for review :) , and its okay i don't care about indiahacks i only just registered :P

**Comment by abhsag24** [comment]
ready for review :)

**Comment by sudheesh001** [comment]
As discussed one more test to be added @abhsag24 :smile: I like where this is going.

**Comment by abhsag24** [comment]
added the test @sudheesh001 @sils1297 :)

**Comment by abhsag24** [comment]
https://github.com/abhsag24/coala-bears/commit/ba905367df5fdeb0c504334507a2e8fc699982d3 for reference, ready for review :)

**Comment by sils1297** [comment]
related: https://github.com/coala-analyzer/coala-bears/issues/37

**Comment by sils1297** [comment]
marking blocked by the annotation bear, would be nice to get it for the release.

**Comment by abhsag24** [comment]
@sils1297  it might not be possible for the release, since after the `AnnotationBear` , this bear calls for a complete refactoring. 
Though i'm already on it and it looks much cleaner than this monster!

**Comment by abhsag24** [comment]
Closing in favor of https://github.com/coala-analyzer/coala-bears/pull/468

**Pull request closed without merging**
