### PR TITLE
GoVetBear: Correct category typo

### PR DESCRIPTION
**Pull request by sils1297**

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
Hey I think we settled somewhere to change typo commit messages something like:
``GoVetBear: Change cateory->category``? it would look better and make more sense

**Comment by sils1297** [comment]
@Adrianzatreanu there you go

**Comment by Adrianzatreanu** [comment]
hate to make you repush for that, but shouldnt it be enclosed in backticks now that you changed it like this :D ?

**Comment by Adrianzatreanu** [comment]
c83937e ack

**Comment by Adrianzatreanu** [comment]
you reack it if you decide to repush, i think its rather ok both ways

**Comment by sils1297** [comment]
@stevepeak why's coverage not appearing? It is deployed in our CI.

**Comment by hypothesist** [comment]
@sils1297 FWIW the corresponding Codecov: https://codecov.io/gh/coala-analyzer/coala-bears/commit/c83937e3318329fab749dc157de3d78740f89fa1

**Comment by Adrianzatreanu** [comment]
@sils1297 it sometimes happens to me when the appveyor builds fail and i restart them. it is fixed by repushing usually :)

**Comment by stevepeak** [comment]
@sils1297 i just restarted the notifications job and it posted. With that being said: I'm not sure at this time why did not fire before...

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@stevepeak I did the same as @Adrianzatreanu mentioned, the appveyor build had a nondeterministic failure (they sometims have network problems) and I restarted it

**Pull request merged**
