### PR TITLE
Sils/0.2.1

### PR DESCRIPTION
**Pull request by sils1297**

### CODE REVIEW

**Comment by sils1297** [comment]
backport PR for https://github.com/coala-analyzer/coala-bears/pull/408

**Comment by AbdealiJK** [comment]
ack 5b0beda 6a4806739dc709fc3f30a617966cea20ed117eab 1d673d2 ecf3ad7c40b54a827f5458a9f927d8b5e63d02cd

**Comment by AbdealiJK** [comment]
reack 3addac1

**Comment by sils1297** [comment]
reack
f42176d perl: Add __init__.py (missing)
36c0b4c scala: Add __init__.py (missing)
0571fbf setup: Correct package exclusion

**Comment by sils1297** [comment]
reack 50e484d

**Comment by AbdealiJK** [comment]
ack 737a3e0

**Comment by AbdealiJK** [comment]
reack 50e484d

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
