### PR TITLE
bears/bash: Add ShellCheckBear

### PR DESCRIPTION
**Pull request by tushar-rishav**
The ShellCheckBear uses `shellcheck` to parse the file and returns
the issues suggested by the linter.

Fixes https://github.com/coala-analyzer/coala-bears/issues/20

### CODE REVIEW

**Comment by sils1297** [comment]
commit message has a typo fwiw

**Comment by tushar-rishav** [comment]
@sils1297  Oh just saw that. Will fix it :P

**Comment by SanketDG** [comment]
@tushar-rishav Can you name the folder as `shell` in which you are inserting the bear? `bash` is not the only shell.

**Comment by AbdealiJK** [comment]
ack 363bb04

**Comment by AbdealiJK** [comment]
@rultor merge

**Pull request merged**
