### PR TITLE
Move `bears.natural_language.MarkdownBear` to a new "markdown" folder

### PR DESCRIPTION
**Pull request by djkonro**
Fixes https://github.com/coala-analyzer/coala-bears/issues/208

### CODE REVIEW

**Comment by AbdealiJK** [comment]
@djkonro Please take a look at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html
Your commit message doesnt follow the rules stated there

**Comment by Adrianzatreanu** [comment]
I think this looks good. Supposing it passes all the tests, im ack'ing it.

**Comment by AbdealiJK** [comment]
ack e83e6c9

**Comment by AbdealiJK** [comment]
@Adrianzatreanu you dont need to wait for tests to ack ... You can unack it later if necessary

**Comment by Adrianzatreanu** [comment]
but you acked with appveyor not ready yet :p

**Comment by AbdealiJK** [comment]
@rultor merge

**Pull request merged**
