### PR TITLE
ClangComplexityBear: Make external attribs private

### PR DESCRIPTION
**Pull request by arafsheikh**
See https://github.com/coala-analyzer/coala/pull/2337#discussion_r69554434

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
yeah the commit is good. but regarding the message, im thinking you chose ``attribs`` instead of ``attributes`` to not go over 50 chars?

**Comment by arafsheikh** [comment]
yes

**Comment by Adrianzatreanu** [comment]
maybe change to: ``Make cursor_kinds private`` ? to be even more explicit?

**Comment by Adrianzatreanu** [comment]
i think you should add double ticks. does it exceed if you do :D ? cuz its about a certain attribute..

**Comment by Adrianzatreanu** [comment]
nope, it has 50, add double backticks :D im cancelling your builds for this one

**Comment by Adrianzatreanu** [comment]
ack 82f54c0

**Comment by arafsheikh** [comment]
@rultor merge

**Comment by Adrianzatreanu** [comment]
reack 9e5b42f

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
