### PR TITLE
bears/scala: Add bear for scala using scalastyle

### PR DESCRIPTION
**Pull request by ravinimmi**
Fixes: https://github.com/coala-analyzer/coala-bears/issues/64

### CODE REVIEW

**Comment by sils1297** [comment]
@ravinimmi you know what to do when gitmate yields results, right? :)

**Comment by ravinimmi** [comment]
@sils1297 Yes :)

**Comment by ravinimmi** [comment]
@sils1297 Yeah there is a bug still left. Tests are not able to read the config file that is generated at runtime.

**Comment by sils1297** [comment]
Can you please announce bugs when you submit stuff for review? We don't
want buggy stuff merged :/

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-02-24 23:29 GMT+01:00 Ravi Kumar Nimmi <notifications@github.com>:

**Comment by sils1297** [comment]
ah tests fail anyway, sorry was just reading through mails

**Comment by sils1297** [comment]
@ravinimmi need help debugging? Does it work locally?

**Comment by ravinimmi** [comment]
@sils1297 Thanks. I can manage. Actually I added the config file recommended by scalastyle. Thats why my good_file has also become bad.

**Comment by sils1297** [comment]
unack 63584cb dde084b

**Comment by sils1297** [comment]
ack 7bcc78  f1ac043

**Comment by sils1297** [comment]
ack 4b02a45 ab5d031

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
