### PR TITLE
Removed the Comma

### PR DESCRIPTION
**Pull request by seblat**

### CODE REVIEW

**Comment by Uran198** [comment]
Thanks for your PR!
Please read: http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html
We require imperative present tense for commit message.

**Comment by Uran198** [comment]
unack ccff7431f98f02a707f22f92e90dadcdbd1522d2

**Comment by SanketDG** [comment]
@seblat Can you remove the `.py` in your commit message:

```
ESLintBearTest: Remove unneeded Comma
```

Also add Fixes <issue url here> in the commit message body.

**Comment by SanketDG** [comment]
unack 241bef9

**Comment by abhsag24** [comment]
unack b4afdbd @seblat  as stated in the guidelines we want you to add a `Fixes: <Full url of issue>` in the commit message

**Comment by abhsag24** [comment]
unack 6f741e6 why the capital 'C' in comma in the commit message? sorry for nitpicking, everything else looks fine  :)

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala-bears/pull/309/commits/1843dd48741aa56d674af615431685acfb1093ce

**Comment by sims1253** [comment]
see https://github.com/coala-analyzer/coala-bears/pull/310

**Pull request closed without merging**
