### PR TITLE
bears/yaml: Add bear for YAML using yamllint

### PR DESCRIPTION
**Pull request by ravinimmi**
Fixes: https://github.com/coala-analyzer/coala-bears/issues/60

### CODE REVIEW

**Comment by sils1297** [comment]
ok the file renaming should also solve the tests, other than that it looks fine - seeing forward to the next iteration :)

**Comment by ravinimmi** [comment]
@sils1297 @AbdealiJK  Please review.

**Comment by sils1297** [comment]
ack 9f446ed

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
