### PR TITLE
CheckstyleBear: Handle column field correctly

### PR DESCRIPTION
**Pull request by arafsheikh**
Fixes https://github.com/coala-analyzer/coala-bears/issues/450

### CODE REVIEW

**Comment by arafsheikh** [comment]
There can be two types of output:
`[WARN] file.java:59:20: Message [Rule]`
or,
`[WARN] file.java:59: Message [Rule]`

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala-bears/pull/451/commits/a651771b7ec1be248ecc30c6c11909b777d7fc57 , please rebase and merge

**Comment by Makman2** [comment]
ah okay .+1:

**Comment by sils1297** [comment]
reack 320421e

**Comment by arafsheikh** [comment]
But if I merge won't the tests fail for everyone afterwards?

**Comment by sils1297** [comment]
you can't merge it anyway since tests are failing, why are they failing anyway? I thought they were passing

**Comment by SanketDG** [comment]
ack 0fef458

**Comment by arafsheikh** [comment]
@rultor merge

**Pull request merged**
