### PR TITLE
bears/cmake: Add CMakeLintBear

### PR DESCRIPTION
**Pull request by nishant-mor**
Fixes https://github.com/coala-analyzer/coala-bears/issues/127

### CODE REVIEW

**Comment by sils1297** [comment]
ack 0799f83

**Comment by nishant-mor** [comment]
wait i forgot to save the file

**Comment by sils1297** [comment]
ah right comment still missing

**Comment by sils1297** [comment]
(cancelled your builds)

**Comment by sils1297** [comment]
ack 6092da3

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
