### PR TITLE
docs: build docs using sphinx

### PR DESCRIPTION
**Pull request by vivek425ster**
Added code to build docs using sphinx and also added 
sphinx compile to docs command in circle CI. Also added 
sphinx as a dependency in docs-requirements.txt.

Fixes https://github.com/coala-analyzer/coala-bears/issues/210

### CODE REVIEW

**Comment by sils1297** [comment]
unack fb9aac4, also `build` -> `Build` in the commit message

**Comment by vivek425ster** [comment]
@sils1297 Yes setup.py docs should also work.
I did this since in coala also it is like this
https://github.com/coala-analyzer/coala/blob/master/circle.yml#L27
Yes i tested it locally it is working.

**Comment by sils1297** [comment]
@vivek425ster with tested locally I mean build the documentation *and* look at it if it's sane ;)

**Comment by sils1297** [comment]
unack foo commit  daa51aa :)

**Comment by vivek425ster** [comment]
@sils1297 @AbdealiJK I am clsoing this PR.
Somehow messed it. Sorry 
Will send a new PR soon.

**Comment by sils1297** [comment]
all mess can be corrected with a blunt push --force, just saying, we really
want you to learn how to use git properly, there's no way around it if you
want to work with us. And if you learn that you'll never find the need to
close a PR because of mess again because you can get everything right in
git ;)

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-11 10:20 GMT+01:00 vivek425ster <notifications@github.com>:

**Comment by vivek425ster** [comment]
@sils1297 I am unable to reopen PR. ?

**Comment by sils1297** [comment]
did you delete your fork? :(

**Comment by sils1297** [comment]
then you basically threw everything away, review comments, code and so on and thus you can't reopen it.

**Comment by vivek425ster** [comment]
@sils1297 no I din't deleted my fork . I just force pushed the branch

**Comment by vivek425ster** [comment]
https://github.com/vivek425ster/coala-bears/tree/issue%23202

**Comment by vivek425ster** [comment]
When i hove over Reopen and comment it says The issue#202 branch was force-pushed or recreated :(

**Comment by vivek425ster** [comment]
So may be can't reopen a PR if we force-push a branch,.

**Comment by sils1297** [comment]
ah if you force push while the PR is closed it doesn't pick it up to preserve state I guess so you need an open PR and then force pushing will update it... anyway this way you can create a new one

**Pull request closed without merging**
