### PR TITLE
README: Update on fluency

### PR DESCRIPTION
**Pull request by Adrianzatreanu**
The paragraphs are now moved a little, titles
are shown with '-' instead of '='.

Idea started by @cw1

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
referencing and closing https://github.com/coala-analyzer/coala-bears/pull/273

**Comment by tushar-rishav** [comment]
LGTM :+1:

**Comment by tushar-rishav** [comment]
ack 1e39d8a

**Comment by Adrianzatreanu** [comment]
not merging untill @sils1297 sees this, tagged you to find it easier.

**Comment by sils1297** [comment]
ack 1e39d8a

**Comment by Adrianzatreanu** [comment]
Ah cool, i will rebase it when i get to my laptop :)

**Comment by sils1297** [comment]
@Adrianzatreanu when will that be? Does it pay off that I do it manually now?

**Comment by Adrianzatreanu** [comment]
sorry, been eatin', it's in 3 minutes.

**Comment by sils1297** [comment]
guess I can wait that long :P

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-04-10 11:07 GMT+02:00 Zatreanu Adrian-Gabriel <notifications@github.com

**Comment by Adrianzatreanu** [comment]
reack 29c72dd

**Comment by sils1297** [comment]
reack 29c72dd

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
