### PR TITLE
Refactor: Change ElementTree import and references

### PR DESCRIPTION
**Pull request by jyeray**

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
Hey, first of all, why is this needed? If there's an issue that is being fixed by this commit, you should place it as ``Fixes issue_link`` in the commit message! 
Also, your commit message needs some work: http://coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html here if you want to perfect in writing amazing commits.

**Comment by Adrianzatreanu** [comment]
Long story short, it should be something like: ``Filechanged: SubjectInPresentTense(Change X)``
``newline``
``Fixes url``

**Comment by Adrianzatreanu** [comment]
Hey it seems you created 2 commits instead of changing the last one. Now you will have to do a ``git rebase -i origin`` and read the instructions there. Basically you need to remove the unwanted lines there and keep only the commits you want.

**Comment by Adrianzatreanu** [comment]
Now regarding the commit message, please change it as i said earlier: it gives no information about whatsoever file/bear is modified. Try changing shortlog to something like ``CPDBear: Change ElementTree import`` maybe? :)

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala-bears/pull/546/commits/67ebdb4d090075425dc8c7c9ef1a3274eebece30

**Comment by Adrianzatreanu** [comment]
ack 67ebdb4

**Comment by Makman2** [comment]
So you don't have to bother with a rebase, #550 takes over :)

**Pull request closed without merging**
