### PR TITLE
PyLintBear: Use origin regex field

### PR DESCRIPTION
**Pull request by Makman2**
Allows to disable single rules via ignore statements inside code.

### CODE REVIEW

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala-bears/pull/426/commits/7d6e9a451cd2b941ea61d7bc92288bc1a71fde36 (will need a rebase though I guess)

**Comment by sils1297** [comment]
alright, rebase please!

**Comment by Makman2** [comment]
reack 7d6e9a4

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
