### PR TITLE
RlintBear: refactor prerequisite checking

### PR DESCRIPTION
**Pull request by SanketDG**
For a prerequisite command to run, now we can use
prerequisite_command for the command to run and
prerequisite_fail_msg for the error message.

### CODE REVIEW

**Comment by AbdealiJK** [comment]
23a1002 ready

**Comment by AbdealiJK** [comment]
rebase needed

**Comment by tushar-rishav** [comment]
reack  4f48511

**Comment by Adrianzatreanu** [comment]
unack 4f48511

**Comment by Adrianzatreanu** [comment]
reack 4f48511

**Comment by SanketDG** [comment]
@rultor merge

**Pull request merged**
