### PR TITLE
requests_mock: move to test-requirements

### LINKED ISSUE #180: requests_mock: Move to test-requirements
requests_mock is used for testing InvalidLinkBear.

It's currently in requirements.txt
We should move it to test-requirements.txt

### PR DESCRIPTION
**Pull request by mukeshmk**
Move requests_mock from requirements to test-requirements

Fixes https://github.com/coala-analyzer/coala-bears/issues/180

### CODE REVIEW

**Comment by sils1297** [comment]
hey, I don't have a lot of time but http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html can help you getting your commit into good shape - thanks for your contribution!

**Comment by sils1297** [comment]
ping us at https://gitter.im/coala-analyzer/coala any time if you need help

**Comment by sils1297** [comment]
b74d95e needs work

**Comment by Adrianzatreanu** [comment]
Hey, as @sils1297 said, your commit message needs some work. You can edit it by typing ``git commit --amend``. It should have a HEAD which is: ``filechanged: change`` , a BODY explaining why the change was made, and a footer which says ``Fixes <issue_FULL_link>`` . also, everywhere you should use present tense :)

**Comment by mukeshmk** [comment]
@sils1297 Is it fine now ?

**Comment by tushar-rishav** [comment]
@mukeshmk  Hey! Your commit should follow certain guidelines. Did you read [Writing good commits](http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html) ? For some hint you can see commit logs. For any further help, ping us on [Gitter](https://gitter.im/coala-analyzer/coala)

**Comment by abhsag24** [comment]
@mukeshmk are you aware that you can just do `git commit --amend` and then push and your PR will update automatically, you don't have to create a new PR  , do leave a message on [gitter](https://gitter.im/coala-analyzer/coala)  if you need any help with any of this :)

**Pull request closed without merging**
