### PR TITLE
Makman2/anti shell inject

### PR DESCRIPTION
**Pull request by Makman2**
This PR adapts the changes from https://github.com/coala-analyzer/coala/pull/1992.
Cross tested on https://github.com/coala-analyzer/coala-bears/pull/314.

### CODE REVIEW

**Comment by sils1297** [comment]
is this blocked by another PR? It's definitely not pending review FWIW...

**Comment by Makman2** [comment]
blocked by https://github.com/coala-analyzer/coala/pull/1992

**Comment by SanketDG** [comment]
ack 576afc4 b27a901 7767584 345633e

**Comment by sils1297** [comment]
ack 576afc4 b27a901 7767584 345633e

**Comment by sils1297** [comment]
ack 576afc4 b27a901 7767584 345633e

**Comment by sils1297** [comment]
ack b27a901 7767584 345633e

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
