### PR TITLE
0.8.1 bugfix release

### PR DESCRIPTION
**Pull request by sils1297**

### CODE REVIEW

**Comment by sils1297** [comment]
backport for bugfixes to be released as 0.8.1

**Comment by underyx** [comment]
ack https://github.com/coala-analyzer/coala-bears/pull/764/commits/6f345c7dd6b95eaf4d3560895514b6253c4cc5a3 https://github.com/coala-analyzer/coala-bears/pull/764/commits/c3db8fd57e234b800e8daa2fbd197db13fa634d0
reack https://github.com/coala-analyzer/coala-bears/pull/764/commits/7ac746373d7f2ebbe03bc6b2b0cf23c2e2be3c33

**Comment by sils1297** [comment]
ack c3db8fd

**Comment by underyx** [comment]
@rultor merge

**Pull request merged**
