### PR TITLE
bears: Use coala-utils for string processing

### PR DESCRIPTION
**Pull request by arafsheikh**

### CODE REVIEW

**Comment by abhsag24** [comment]
@arafsheikh shouldn't the commits be reordered? i find it more logical to update coala first and then change the things broken by the update? or is it something that i don't get?

**Comment by arafsheikh** [comment]
@abhsag24 It won't have any effect, but yeah it's logically correct. Updated :)

**Comment by abhsag24** [comment]
ack d024ce5, 359afc5

**Comment by arafsheikh** [comment]
@rultor merge

**Pull request merged**
