### PR TITLE
ClangComplexityBear: Move to c_languages

### PR DESCRIPTION
**Pull request by sils1297**
This has nothing to do with the code clone detection.

### CODE REVIEW

**Comment by sils1297** [comment]
CC @Uran198 for review

**Comment by sils1297** [comment]
ah tests will fail due to not adjusting the test path

**Comment by Uran198** [comment]
ack 11f738f

**Comment by sils1297** [comment]
ack 11f738f

I just deployed a fix for the problem which caused GitMate to ignore your comment, should work now

**Comment by sils1297** [comment]
ack 11f738f ?

**Comment by sils1297** [comment]
hm possibly the server needed a few more seconds to start...

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
