### PR TITLE
Mentiondocs

### PR DESCRIPTION
**Pull request by Adrianzatreanu**

### CODE REVIEW

**Comment by sils1297** [comment]
Are you really planning to merge that dot commit

**Comment by Adrianzatreanu** [comment]
Omg this is like the funniest thing that has happened in a while :D

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala-bears/pull/719/commits/c91637f2679cc3ee6331957b787d823a7049e5ce

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala-bears/pull/719/commits/824d32d4fcc5885f1c79ab671daa64cdd442f0e3

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
