### PR TITLE
README: Fix capitalization

### PR DESCRIPTION
**Pull request by devMoxie**
Fixes https://github.com/coala-analyzer/coala-bears/issues/387

### CODE REVIEW

**Comment by Makman2** [comment]
ack ab70b12

**Comment by sils1297** [comment]
Hi,

it looks like your PR is out of date and needs a rebase. [This page](http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html) may help you to get started on this. (*Do not press the update branch button. It's evil.*)

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

Ping us on [our gitter channel](https://gitter.im/coala-analyzer/coala) if you need help or drop by at Portland Ballroom 253!

**Comment by sils1297** [comment]
please also comment when you rebase so I get an email

**Comment by Makman2** [comment]
@devMoxie ping :)

**Comment by devMoxie** [comment]
Sorry, I went off the grid for a few days. I will attempt a rebase today.

**Comment by sils1297** [comment]
no problem, let us know if you need help :)

**Comment by devMoxie** [comment]
Is this correct,
`git remote add upstream https://github.com/coala-analyzer/coala.git` ?

Or, did you mean,
`git remote add upstream https://github.com/coala-analyzer/coala-bears.git` ?

**Comment by sils1297** [comment]
yes, coala-bears

**Comment by devMoxie** [comment]
I'm having a hard completing the rebase.

    devmoxie: coala-bears $ git remote -v
    downstream	https://github.com/devMoxie/coala-bears.git (fetch)
    downstream	https://github.com/devMoxie/coala-bears.git (push)
    origin	https://github.com/coala-analyzer/coala-bears.git (fetch)
    origin	https://github.com/coala-analyzer/coala-bears.git (push)
    upstream	https://github.com/coala-analyzer/coala-bears.git (fetch)
    upstream	https://github.com/coala-analyzer/coala-bears.git (push)

    devmoxie: coala-bears $ git checkout attempt-rebase
    Switched to branch "attempt-rebase"

    devmoxie: coala-bears $ git fetch upstream
    remote: Counting objects: 10, done.
    remote: Total 10 (delta 8), reused 8 (delta 8), pack-reused 2
    Unpacking objects: 100% (10/10), done.
    From https://github.com/coala-analyzer/coala-bears
     * [new branch]      Makman2/rubybier -> upstream/Makman2/rubybier

    devmoxie: coala-bears $ git rebase --interactive upstream/master
    Successfully rebased and updated refs/heads/attempt-rebase.

    devmoxie: coala-bears $ git push --force
    fatal: The current branch attempt-rebase has no upstream branch.

Any thoughts? Is this the best place to discuss this or should I post this on gitter?
    To push the current branch and set the remote as upstream, use

        git push --set-upstream origin attempt-rebase

    devmoxie: coala-bears $ git push --set-upstream origin attempt-rebase
    remote: Permission to coala-analyzer/coala-bears.git denied to devMoxie.
    fatal: unable to access 'https://github.com/coala-analyzer/coala-bears.git/': 
    The requested URL  returned error: 403

**Comment by sils1297** [comment]
Hey, you checked out a new branch and git doesn't know where to push it. It's best if you checkout your original branch, then do the rebase there and push force it up.

**Comment by sils1297** [comment]
people on gitter will also be able to help you

**Comment by Makman2** [comment]
reack 467c771

**Comment by Adrianzatreanu** [comment]
reack 9ac9639

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
