### PR TITLE
InvalidLinkBear: Add warning about visiting URLs

### PR DESCRIPTION
**Pull request by underyx**
Fixes https://github.com/coala-analyzer/coala-bears/issues/490

### CODE REVIEW

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala-bears/pull/491/commits/a386eaa240a4c19bafd738e965d1cf7821175611

**Comment by sils1297** [comment]
@stevepeak why is codecov not reporting here? Seems a report is there

**Comment by stevepeak** [comment]
> @sils1297 PS https://github.com/coala-analyzer/coala-bears/compare/master...stevepeak:patch-3

The system timed out, restarted job and it worked. I'll see to a way to retry if issues like this occur.

**Comment by SanketDG** [comment]
this was needed, thanks @underyx :smile:

**Comment by SanketDG** [comment]
@rultor merge

**Pull request merged**
