### PR TITLE
bears/__init__.py:import constants

### PR DESCRIPTION
**Pull request by Nosferatul**
Add the version constants from Constants.py. Add variable "__version__".

Fixes https://github.com/coala-analyzer/coala-bears/issues/84

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
Your branch seems to be outdated. Could you do a git pull from master and try again?

**Comment by sils1297** [comment]
why was this closed?

**Comment by Adrianzatreanu** [comment]
he seems to have merged the master branch and apparently opened a new PR.

**Comment by sils1297** [comment]
people do weird things

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-02-28 21:19 GMT+01:00 Zatreanu Adrian-Gabriel <notifications@github.com

**Pull request closed without merging**
