### PR TITLE
Unify settings names

### PR DESCRIPTION
**Pull request by Asnelchristian**
Related to https://github.com/coala-analyzer/coala-bears/issues/460

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
ack a0b6980e8bcd0fc733924f207055ba85e49f55d8

**Comment by Adrianzatreanu** [comment]
ack 22db957b84736808add08b3e0529dd8f42f4014f

**Comment by Adrianzatreanu** [comment]
ack 0fc64c10fa4fbd73b78ebbea28a690f8ebff5f9d

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala-bears/pull/654/commits/8e85c82e8c74c0fc9a4db804f59da585e9dbf757 https://github.com/coala-analyzer/coala-bears/pull/654/commits/ae585888b9d8f6c7fb197787d0c71749d6087eb9

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala-bears/pull/654/commits/bdb47df0b912105d4b4890c74c7f4f91077cbd69 https://github.com/coala-analyzer/coala-bears/pull/654/commits/9a1ebbaf16afc2992d26aa86244fb79b8beeaad1 https://github.com/coala-analyzer/coala-bears/pull/654/commits/f853cbefcc7cb9eb1fe891c81c378bad591ee0a3

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
