### PR TITLE
setup.cfg: Ignore file test-requirements.txt

### PR DESCRIPTION
**Pull request by mr-karan**
I have omitted the unwanted file (test-requirements.txt) in setup.cfg as it gets picked up when running py.test because of the test- prefix.

Fixes https://github.com/coala-analyzer/coala-bears/issues/71

### CODE REVIEW

**Comment by AbdealiJK** [comment]
Why make a new branch ? Just modify the old branch

**Comment by sils1297** [comment]
also this needs a rebase

**Comment by sils1297** [comment]
better wait ~5 min with the rebase, I'm just merging something. Then fetch and rebase again.

**Comment by SanketDG** [comment]
@mr-karan This doesn't fix the issue. What you are doing removes it from coverage, but it still gets counted as a test.

You need to add `--ignore=<file>` to `addopts` in setup.cfg. Then no need to ignore it in coverage.

**Comment by mr-karan** [comment]
Fixed :  https://github.com/coala-analyzer/coala-bears/pull/134

**Pull request closed without merging**
