### PR TITLE
Rename IndentBear to GNUIndentBear

### PR DESCRIPTION
**Pull request by MayankVachher**
Fixes https://github.com/coala-analyzer/coala-bears/issues/120

### CODE REVIEW

**Comment by hypothesist** [comment]
@MayankVachher run coala over the whole repo and once.

**Comment by AbdealiJK** [comment]
@MayankVachher also, the same thing about the git commit message (shortlog)

**Comment by sils1297** [comment]
https://github.com/coala-analyzer/coala-bears/pull/248/commits/a5cbf07fbc5dd1ed0e11ec4cb80721a160405ad9 is ready

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
