### PR TITLE
tests/js/ESLintBear: remove unnecessary import

### PR DESCRIPTION
**Pull request by jarifibrahim**

### CODE REVIEW

**Comment by sils1297** [comment]
hey, looks good, seems like your commit message needs some work, we have some info about that here: http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html , specifically you'll want to mention the issue

**Comment by sils1297** [comment]
also capitalization isn't correct yet, hope it helps! 
https://github.com/jarifibrahim/coala-bears/commit/ee1291b7f4410ccb9e3a9a855d96b88228c638bb needs work

**Comment by jarifibrahim** [comment]
Thanks for the feedback. Should I just delete the branch and push a new one or rename the commit message using the `git commit --amend` command?

**Comment by sils1297** [comment]
just amend it and force push :)

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-14 13:45 GMT+01:00 Ibrahim Jarif <notifications@github.com>:

**Comment by sils1297** [comment]
neat, https://github.com/jarifibrahim/coala-bears/commit/759fe00d1b92a5a245883251e1e8031ccc14cafd is ready

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
