### PR TITLE
Wiki

### PR DESCRIPTION
**Pull request by Adrianzatreanu**

### CODE REVIEW

**Comment by sils1297** [comment]
rather link to https://github.com/coala-analyzer/bear-docs please

**Comment by sils1297** [comment]
unack 57aea5e

**Comment by sils1297** [comment]
ack 9219f87

**Comment by sils1297** [comment]
rebase and merge!

**Comment by Adrianzatreanu** [comment]
reack ac11cef

**Comment by Adrianzatreanu** [comment]
reack 443b4da

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
