### PR TITLE
bears/natural_language: Moved reSTLintBear.py

### PR DESCRIPTION
**Pull request by manojpandey**
Move `bears.natural_language.reSTLintBear` to a new "rst" folder

Fixes https://github.com/coala-analyzer/coala-bears/issues/209

### CODE REVIEW

**Comment by sils1297** [comment]
hey, could you look through http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html ? That should help you getting your commit message right. http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html can help you changing your commit. Ping us on gitter if you need anything.

**Comment by manojpandey** [comment]
Thanks @sils1297 for the pointer. I forgot the maximum character length of shortlog. Fixed that.
Hopefully, now it'll be fine. :)

**Comment by manojpandey** [comment]
Got the errors, tests are failing, fixing them :)

**Comment by sils1297** [comment]
Cool, thanks. Marking wip

**Comment by AbdealiJK** [comment]
The commit message is still wrong

**Comment by manojpandey** [comment]
@AbdealiJK : Sorry about that. What should I possibly change? :)
Should I separate 

```
Moved `bears/natural_language/reSTLintBear.py` to a new "rst" folder.
So, new file is now at 'bears/rst/reSTLintBear.py.'
Also moved the test file, reSTLintBearTest.py to tests/rst/
from tests/natural_language/
```
as
```
Moved `bears/natural_language/reSTLintBear.py` to a 
new "rst" folder. The file is now at 'bears/rst/reSTLintBear.py.'

Also moved the test file, reSTLintBearTest.py to tests/rst/ 
from tests/natural_language/
```

**Comment by AbdealiJK** [comment]
Hey, the problem is that the terms is in past tense. It should be imperative
Can you check the example in the docs? And maybe other commits on master?
Basically "moved file 1" should be "move file 1" and so on

-----Original Message-----

**Comment by manojpandey** [comment]
Thanks @AbdealiJK for pointing it out specifically :)
```
bears/natural_language: Move reSTLintBear.py
    
    Move `bears/natural_language/reSTLintBear.py`
    to a new "bears/rst" folder.
    The new file is now at 'bears/rst/reSTLintBear.py'
    
    Move 'tests/natuarl_language/reSTLintBearTest.py'
    to new "tests/rst" folder
    
    Fixes https://github.com/coala-analyzer/coala-bears/issues/209

```

Looks good now ?

**Comment by AbdealiJK** [comment]
yep :+1:

**Comment by SanketDG** [comment]
ack c97877d

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
