### PR TITLE
Issue#259

### PR DESCRIPTION
**Pull request by vivek425ster**

### CODE REVIEW

**Comment by SanketDG** [comment]
ack 69dfba4

**Comment by Adrianzatreanu** [comment]
You have some problems with the commit message on the exitcode one. First of all, I don't think we use past tense in the body, it should be Adds; and also, on the last line, grammatically correct is "built".

**Comment by sils1297** [comment]
in the body past tense is ok if it's needed

**Comment by Adrianzatreanu** [comment]
unack 12eda63

**Comment by Adrianzatreanu** [comment]
correct is still ``built`` :D so unacking it for now

**Comment by sils1297** [comment]
ack 
0a99c06

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
