### PR TITLE
CPDBear: Fix typo omparison to comparison

### PR DESCRIPTION
**Pull request by Rulestormer**
Fixed the typo.

Closes https://github.com/coala-analyzer/coala-bears/issues/606

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
hey, your change is really good, but your commit message could use some work.
First of all, commit body should be in present tense: ``Fixes the typo.``
Secondly, you could change the commit shortlog to look better, such as: CPDBear: Change ``omparison``->``comparison``

**Comment by Asnelchristian** [comment]
Hi,

it seems that your commit message doesn't contain enough information. Don't worry, most people don't know about good commit messages when they join us, including very experienced developers :) Standards vary from project to project.

The most important part is the first line of your commit message - maintainers will use it to read through a large number of commits and thus it's important that it's short but most importantly concise. I'd heartily recommend reading http://coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html !

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).

Cheers!

**Comment by Asnelchristian** [comment]
SORRY

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala-bears/pull/669/commits/731d05052742504e715708d6700de21e4953f18a

**Comment by sils1297** [comment]
https://github.com/coala-analyzer/coala-bears/pull/669/commits/32c76751c77db9d0800401406a2b13975c384ecd ack

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
