### PR TITLE
requirements.txt: Update coala

### PR DESCRIPTION
**Pull request by hypothesist**

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
this is a very strong commit, @hypothesist , have you worked hard for it :D ?

**Comment by Adrianzatreanu** [comment]
ack 275ec8d

**Comment by hypothesist** [comment]
@Adrianzatreanu GitMate asked you to review this cautiously. Did you? :P

**Comment by Adrianzatreanu** [comment]
of course, as I always! tested it on my own machine

**Comment by Adrianzatreanu** [comment]
@hypothesist why is codecov not doing stuff? if it stays like this, repush and reack :D

**Comment by hypothesist** [comment]
reack https://github.com/coala-analyzer/coala-bears/pull/567/commits/9742832b5f74c03ad2c679f24778676e5d21da23

**Comment by Adrianzatreanu** [comment]
codecov has too  many tests to run, be patient

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
