### PR TITLE
GitCommitBear.py: set body_line_length to 72

### PR DESCRIPTION
**Pull request by sims1253**

### CODE REVIEW

**Comment by mr-karan** [comment]
@sims1253 There's some issue with the commit message(there's none fwiw), please take a look at https://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html

unack https://github.com/coala-analyzer/coala-bears/pull/307/commits/6deb22f3c96208089967d0dec1b6877def103d37

**Comment by mr-karan** [comment]
unack https://github.com/coala-analyzer/coala-bears/commit/470dc3c99725797d961cfd70f4bbfa5f8676324c

**Comment by Adrianzatreanu** [comment]
Add newline between header and body :p

**Comment by tushar-rishav** [comment]
unack b0496ca

**Comment by tushar-rishav** [comment]
@Adrianzatreanu Change the label to wip once reviewed please

**Comment by SanketDG** [comment]
unack ffb1537

**Comment by SanketDG** [comment]
Tests failing @sims1253

**Comment by Uran198** [comment]
Both the changes should be in the one commit, as they don't make sense one without another.
unack c063d8a

**Comment by SanketDG** [comment]
ack 84789cf

**Comment by sims1253** [comment]
see https://github.com/coala-analyzer/coala-bears/pull/310

**Pull request closed without merging**
