### PR TITLE
xml: Rename package to xml2

### PR DESCRIPTION
**Pull request by Makman2**
As we put each bear-directory and their subdirectories into the Python
path, our `xml` package shadows the built-in. This makes problems inside
Windows (making the default bears practically unusable).

coala encourages to not import each subdirectory so that built-ins are
not shadowed accidentally, though this is difficult. This is a hotfix so
Windows users can do something with coala again.

### CODE REVIEW

**Comment by sils1297** [comment]
@Makman2 conflicts, test fail

**Comment by Makman2** [comment]
I think there's no need now for this PR, I got the real patch :)
closing after the good patch is merged :+1:

**Comment by Makman2** [comment]
the import problem is more problematic than thought... renaming makes still sense

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala-bears/pull/523/commits/74b07c4a247f34e2f46765cc4bbbe7bdee9e9c8e

**Comment by sils1297** [comment]
@Makman2 your builds fail, you forgot to adapt the imports

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala-bears/pull/523/commits/a79e6cba7dd52c20f70a404535f746a33fcdba6d assuming the tests pass

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
