### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by cw1**
Rearranged paragraphs for a better reading fluency and a more logical order.

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
Hey, we made a few changes to our README. You will first need a rebase and then change what you wanted :) Thanks

**Comment by sils1297** [comment]
@Adrianzatreanu would you mind to take over this PR? Basically making a new comment with similar changes, I like his idea and he seems a bit busy atm.

**Comment by Adrianzatreanu** [comment]
@sils1297 wait a second, did we not cherry pick this? i'm pretty sure you did, but it didnt close.

**Comment by Adrianzatreanu** [comment]
i can't find anything, seems to have been something else. im taking over then :)

**Comment by Adrianzatreanu** [comment]
PR moved here https://github.com/coala-analyzer/coala-bears/pull/320 , closing this one;

**Pull request closed without merging**
