### PR TITLE
Empty commit

### PR DESCRIPTION
**Pull request by sils1297**
to see if builds fail here too

### CODE REVIEW

**Comment by sils1297** [comment]
cause for circle failure is https://twitter.com/sfnet_ops/status/752962244200189952

**Comment by sils1297** [comment]
likely

**Comment by sils1297** [comment]
very much likely also for appveyor as checkstyle also is hosted on sourceforge

**Comment by SanketDG** [comment]
This can be closed now?

**Comment by sils1297** [comment]
oh yes, right

**Pull request closed without merging**
