### PR TITLE
unused variables removed

### PR DESCRIPTION
**Pull request by Ana06**

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
Hey, the change is alright I guess, but there's two more things you should work on:

- add the issue-link here if you've come to do this thanks to being assigned to an issue. it should be in the commit message at the end, as ``Fixes url_link``

- work on your commit message. to perfect your skill in writing commit messages, consult http://coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html

**Comment by Adrianzatreanu** [comment]
tl;dr: commit message should be something like: ``GoReturnsBearTest: Remove unused variables``
and the ``Fixes url_link`` if there's the case here.

**Comment by Ana06** [comment]
@Adrianzatreanu I don't know if there is an issue for that, I realised that it was unused while working on another issue.

**Comment by sils1297** [comment]
https://github.com/coala-analyzer/coala-bears/pull/549/commits/2c5667ca6f6c65c4ea21e0f984cfcea6079a0211 is ready

**Comment by sils1297** [comment]
@rultor merge

**Comment by Adrianzatreanu** [comment]
ack 2c5667c

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
