### PR TITLE
generate_packageTest: Patch sys.argv

### PR DESCRIPTION
**Pull request by chriscoyfish**
Refactor clean-up prior to fixing https://github.com/coala-analyzer/coala-bears/issues/597

### CODE REVIEW

**Comment by chriscoyfish** [comment]
Not sure why appveyor is failing...

**Comment by Makman2** [comment]
This is chckstyle,  sometimes it fails to download. Restarted the build :)

**Comment by sils1297** [comment]
CC @Adrianzatreanu

**Comment by sils1297** [comment]
neat! https://github.com/coala-analyzer/coala-bears/pull/677/commits/f48ba047c95122b22333541a72d1ba6b7e9e0b0e is ready

**Comment by sils1297** [comment]
(sorry for letting you wait so long)

**Comment by sils1297** [comment]
It looks like your PR is out of date and needs a rebase. [This page](http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html) may help you to get started on this. (*Do not press the update branch button. It's evil.*)

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix it up for you - just tell us :).

Ping us on [our gitter channel](https://gitter.im/coala-analyzer/coala) if you need help!

**Comment by sils1297** [comment]
reack https://github.com/coala-analyzer/coala-bears/pull/677/commits/283a42348a32df349103e574d58adc93aa5f0af3

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
