### PR TITLE
doc: Add doc_string for execute_bears

### PR DESCRIPTION
**Pull request by heijligen**
Adding the missing doc_string for execute_bear

Closes https://github.com/coala-analyzer/coala-bears/issues/321

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
Hey, your commit seems to have some problems. Either fix them by reading the issues found by gitmate, or simply install coala and run ``coala`` in the command line, which will fix all the issues automatically :)

To install coala, check this: https://github.com/coala-analyzer/coala#installation

**Comment by Adrianzatreanu** [comment]
then after making the right changes, ``git add`` the file again and ``git commit --amend`` to modify the last commit, and ``git push`` again :)

**Comment by Adrianzatreanu** [comment]
Also, regarding the commit message: The commit body should be in present simple, aka ``Adds..`` and end with a period, aka ``.``. About the shortlog, the function is named ``execute_bear`` not ``execute_bears`` :) rest is cool

**Comment by Makman2** [comment]
ignore the circle-CI build, this is a socket error which occurs sporadically. When you fix your PR, a rebuild is triggered anyway and the socket error should disappear --> ci passes :D

**Comment by Adrianzatreanu** [comment]
hey @heijligen you still working on this :) ?

**Comment by sils1297** [comment]
Hi,

do you need help figuring this out? We're all happy to help you on [our gitter channel](https://gitter.im/coala-analyzer/coala), just drop by and ask us anything :)

**Comment by AbdealiJK** [comment]
Closing this, as it's been a while and no response.
Also, it seems someone else has been assigned to the issue now.

**Pull request closed without merging**
