### PR TITLE
CPDBear: Update supported languages

### PR DESCRIPTION
**Pull request by sils1297**

### CODE REVIEW

**Comment by fneu** [comment]
I do notice that there is no commit or PR message, no `closes` or `fixes` etc.
Consider this a friendly reminder in case something should be there

**Comment by fneu** [comment]
ack https://github.com/coala-analyzer/coala-bears/pull/505/commits/d90bd80c85adfeefc14c51466bab48bce7619c53

**Comment by sils1297** [comment]
no issue for that, I just spotted that this supports more languages than we have :)

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
another notice, we should probably use the same language names consistently everywhere, for the supported languages, the coalangs and for cases like this.

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
