### PR TITLE
XMLBear: Yield results from stderr

### PR DESCRIPTION
**Pull request by SanketDG**
XMLBear now will yield results from stdout as well as stderr
to report syntax errors

Fixes https://github.com/coala-analyzer/coala-bears/issues/112

### CODE REVIEW

**Comment by sils1297** [comment]
ack b048c64 , like it :)

**Comment by sils1297** [comment]
will need a rebase in a minute when julia is merged

**Comment by sils1297** [comment]
*that* was fast feel free to merge

**Comment by SanketDG** [comment]
@rultor merge

**Comment by sils1297** [comment]
after the statuses pass ;)

**Comment by SanketDG** [comment]
Oh! I almost skipped a heartbeat, thinking I messed up or something.

**Comment by SanketDG** [comment]
@rultor merge

**Pull request merged**
