### PR TITLE
Remove travis

### PR DESCRIPTION
**Pull request by abhsag24**

### CODE REVIEW

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala-bears/pull/421/commits/b079b2053c364154f74ea812808fd0c75504f1e2 https://github.com/coala-analyzer/coala-bears/pull/421/commits/e45c3ead8a560269661ba5205250af479ef3ad61

**Comment by abhsag24** [comment]
@sils1297  why does travis still show in the checks?

**Comment by sils1297** [comment]
it doesn't now, it did because I told github to require travis for all merges, I changed that now

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
