### PR TITLE
Update release notes

### PR DESCRIPTION
**Pull request by sils1297**

### CODE REVIEW

**Comment by fneu** [comment]
reack https://github.com/coala-analyzer/coala-bears/pull/545/commits/9a336d8a428fdb234b6d9dfabc23ce7d1010bf65 https://github.com/coala-analyzer/coala-bears/pull/545/commits/1533668ff321b65e555916846afe1d7ef5124d12 https://github.com/coala-analyzer/coala-bears/pull/545/commits/226c1fdcc50247401849a14a7811a136a16cb43c

**Comment by hypothesist** [comment]
reack https://github.com/coala-analyzer/coala-bears/pull/545/commits/226c1fdcc50247401849a14a7811a136a16cb43c

for some reason @fneu 's ack didn't work

**Comment by Asnelchristian** [comment]
i think you forgot about the configuration on FormatRBear

**Comment by fneu** [comment]
ack https://github.com/coala-analyzer/coala-bears/pull/545/commits/ad62ea4b3a21c998cc2861e1d453446d593b733 https://github.com/coala-analyzer/coala-bears/pull/545/commits/0b2baa8d948b98d3f29192369986c6a0e751c70 https://github.com/coala-analyzer/coala-bears/pull/545/commits/563c830fdb06be9995a20d826d35c625bd48e2b570

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
