### PR TITLE
bears/xml: Add XMLBear

### PR DESCRIPTION
**Pull request by SanketDG**
check for XML syntax errors using xmllint

Fixes https://github.com/coala-analyzer/coala-bears/issues/32

### CODE REVIEW

**Comment by Redridge** [comment]
@sils1297 maybe also take a look? I find it ok though

**Comment by sils1297** [comment]
I think it'd be better to use gives_corrected, if you have syntax errors it'll give them via stderr which will make coala yield a warning that the file is unlintable which is fine IMO.

**Comment by sils1297** [comment]
though I'm open to opinions

**Comment by sils1297** [comment]
ignoring scrutinizer as it's not required and http://status.scrutinizer-ci.com/

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
