### PR TITLE
generate_package: Add manifest for requirements.txt

### PR DESCRIPTION
**Pull request by Adrianzatreanu**
Also makes the pip requirements install upon
package installation, using setuptools.

### CODE REVIEW

**Comment by Asnelchristian** [comment]
this is good :) for me 
ack https://github.com/coala-analyzer/coala-bears/pull/711/commits/889276720d4ad8d1bc5e25ef383701ee1f86dcab

**Comment by Asnelchristian** [comment]
:+1: :

**Comment by Adrianzatreanu** [comment]
reack 8892767

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
