### PR TITLE
.gitignore : add .swp to gitignore

### PR DESCRIPTION
**Pull request by mayank-agarwal-96**
Fixes https://github.com/coala-analyzer/coala-bears/issues/94

### CODE REVIEW

**Comment by sils1297** [comment]
retriggered builds failing nondeterministically.

Commit message: please remove the *space before the colon* not after, just like normal english ;). Also `add` -> `Add`.

Otherwise good :)

**Comment by sils1297** [comment]
unack  c91067c , this needs some work but is pretty good already :)

**Comment by sils1297** [comment]
ack 37f1594

**Comment by AbdealiJK** [comment]
@rultor merge

**Pull request merged**
