### PR TITLE
requirements: request_mock -> test-requirements

### PR DESCRIPTION
**Pull request by chriscoyfish**

### CODE REVIEW

**Comment by sils1297** [comment]
Hey, http://coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html

**Comment by sims1253** [comment]
Hey there,
You might want to look at our commit message style here:  http://coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html

Specialy the "Issue reference" part.

**Comment by chriscoyfish** [comment]
Fixed the reference link.

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala-bears/pull/477/commits/f9644026066a3360a78a9e78bb854c3965c42890 :)

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@chriscoyfish so this will automatically create a release of coala with your changes in it. Thanks for your contribution, I hope this was a nice experience for you! If you want to go further, we're around at the sprints or as always remotely.

See also https://github.com/coala-analyzer/coala/wiki/coala-Steam-Offer

**Pull request merged**
