### PR TITLE
PerlCritic: changed --config to --profile

### PR DESCRIPTION
**Pull request by gopalmeena**
Fixes https://github.com/coala-analyzer/coala-bears/issues/109

### CODE REVIEW

**Comment by sudheesh001** [comment]
unack 3dccc36

The tense of the commit message can be corrected, please use `change --config to --profile` instead of `changed`

**Comment by AbdealiJK** [comment]
@gopalmeena the commit message is in past tense.

I also notice you're not in the org yet (?) Have you taken a look at http://coala.readthedocs.org/en/latest/Getting_Involved/Newcomers.html ?
I've invited you to the org so we can assign this issue to you.
Please don't solve issues that you're not assigned to (causes confusion and double work). You can comment on an issue if you wish to be assigned to it
 
You can chat with us on gitter if you have any questions.

**Comment by sudheesh001** [comment]
ack 88c1af5

**Comment by AbdealiJK** [comment]
unack 88c1af5

We need a test to make sure this sort of thing doesn't happen !

**Comment by sils1297** [comment]
unack 88c1af5

**Comment by AbdealiJK** [comment]
@gopalmeena could you solve this ? This blocks our next major release which is needed in the next 2 days because of the FOSSAsia conference

**Comment by sils1297** [comment]
test needs to be added and commit message adapted, maybe @AbdealiJK could take this commit brush it up and let him still set as author so we get it ASAP?

**Comment by sils1297** [comment]
https://github.com/coala-analyzer/coala-bears/commit/8a83a635951d4f7a44506250ee49ded2ed6326ba was merged in the meantime

**Pull request closed without merging**
