### PR TITLE
Sils/adri

### PR DESCRIPTION
**Pull request by sils1297**

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
ack b0519c4

**Comment by Adrianzatreanu** [comment]
ack 38eb89c 1d3d7e7 91a9014

**Comment by Adrianzatreanu** [comment]
ack b0519c4

**Comment by sils1297** [comment]
ack 38eb89c 1d3d7e7 91a9014

**Comment by sils1297** [comment]
ack b0519c4

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala-bears/pull/254/commits/b0519c41d4d0d02875086c74c238a912b99ecdd1 ?

**Comment by Adrianzatreanu** [comment]
ack 6a5457f 3c4ce7a 3672819

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
